name: conda_test
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10.12
  - anndata
  - scipy
  - pandas
  - r-base=4.3.1
  - r-remotes=2.5.0
  - r-ggrepel=0.9.6
  - r-ggsignif=0.6.4
  - r-patchwork=1.3.0
  - r-ggplot2=3.5.1
  - r-wgcna=1.73
  - r-tibble=3.2.1
  - r-paletteer=1.6.0
  - r-matrix=1.6-5
  - r-tidyverse=2.0.0
  - r-seurat=5.2.1
  - r-ggpubr=0.6.0
  - r-biocmanager=1.30.25